!record ${OUTPUT_FILE}
SELECT "MARKER", "query1.sql", "",  unix_timestamp();
!run query1.sql;
SELECT "MARKER", "query10.sql", "query1.sql",  unix_timestamp();
!run query10.sql;
SELECT "MARKER", "query11.sql", "query10.sql",  unix_timestamp();
!run query11.sql;
SELECT "MARKER", "query12.sql", "query11.sql",  unix_timestamp();
!run query12.sql;
SELECT "MARKER", "query13.sql", "query12.sql",  unix_timestamp();
!run query13.sql;
SELECT "MARKER", "query14.sql", "query13.sql",  unix_timestamp();
!run query14.sql;
SELECT "MARKER", "query15.sql", "query14.sql",  unix_timestamp();
!run query15.sql;
SELECT "MARKER", "query16.sql", "query15.sql",  unix_timestamp();
!run query16.sql;
SELECT "MARKER", "query17.sql", "query16.sql",  unix_timestamp();
!run query17.sql;
SELECT "MARKER", "query18.sql", "query17.sql",  unix_timestamp();
!run query18.sql;
SELECT "MARKER", "query19.sql", "query18.sql",  unix_timestamp();
!run query19.sql;
SELECT "MARKER", "query2.sql", "query19.sql",  unix_timestamp();
!run query2.sql;
SELECT "MARKER", "query20.sql", "query2.sql",  unix_timestamp();
!run query20.sql;
SELECT "MARKER", "query21.sql", "query20.sql",  unix_timestamp();
!run query21.sql;
SELECT "MARKER", "query22.sql", "query21.sql",  unix_timestamp();
!run query22.sql;
SELECT "MARKER", "query23.sql", "query22.sql",  unix_timestamp();
!run query23.sql;
SELECT "MARKER", "query24.sql", "query23.sql",  unix_timestamp();
!run query24.sql;
SELECT "MARKER", "query25.sql", "query24.sql",  unix_timestamp();
!run query25.sql;
SELECT "MARKER", "query26.sql", "query25.sql",  unix_timestamp();
!run query26.sql;
SELECT "MARKER", "query27.sql", "query26.sql",  unix_timestamp();
!run query27.sql;
SELECT "MARKER", "query28.sql", "query27.sql",  unix_timestamp();
!run query28.sql;
SELECT "MARKER", "query29.sql", "query28.sql",  unix_timestamp();
!run query29.sql;
SELECT "MARKER", "query3.sql", "query29.sql",  unix_timestamp();
!run query3.sql;
SELECT "MARKER", "query30.sql", "query3.sql",  unix_timestamp();
!run query30.sql;
SELECT "MARKER", "query31.sql", "query30.sql",  unix_timestamp();
!run query31.sql;
SELECT "MARKER", "query32.sql", "query31.sql",  unix_timestamp();
!run query32.sql;
SELECT "MARKER", "query33.sql", "query32.sql",  unix_timestamp();
!run query33.sql;
SELECT "MARKER", "query34.sql", "query33.sql",  unix_timestamp();
!run query34.sql;
SELECT "MARKER", "query35.sql", "query34.sql",  unix_timestamp();
!run query35.sql;
SELECT "MARKER", "query36.sql", "query35.sql",  unix_timestamp();
!run query36.sql;
SELECT "MARKER", "query37.sql", "query36.sql",  unix_timestamp();
!run query37.sql;
SELECT "MARKER", "query38.sql", "query37.sql",  unix_timestamp();
!run query38.sql;
SELECT "MARKER", "query39.sql", "query38.sql",  unix_timestamp();
!run query39.sql;
SELECT "MARKER", "query4.sql", "query39.sql",  unix_timestamp();
!run query4.sql;
SELECT "MARKER", "query40.sql", "query4.sql",  unix_timestamp();
!run query40.sql;
SELECT "MARKER", "query41.sql", "query40.sql",  unix_timestamp();
!run query41.sql;
SELECT "MARKER", "query42.sql", "query41.sql",  unix_timestamp();
!run query42.sql;
SELECT "MARKER", "query43.sql", "query42.sql",  unix_timestamp();
!run query43.sql;
SELECT "MARKER", "query44.sql", "query43.sql",  unix_timestamp();
!run query44.sql;
SELECT "MARKER", "query45.sql", "query44.sql",  unix_timestamp();
!run query45.sql;
SELECT "MARKER", "query46.sql", "query45.sql",  unix_timestamp();
!run query46.sql;
SELECT "MARKER", "query47.sql", "query46.sql",  unix_timestamp();
!run query47.sql;
SELECT "MARKER", "query48.sql", "query47.sql",  unix_timestamp();
!run query48.sql;
SELECT "MARKER", "query49.sql", "query48.sql",  unix_timestamp();
!run query49.sql;
SELECT "MARKER", "query5.sql", "query49.sql",  unix_timestamp();
!run query5.sql;
SELECT "MARKER", "query50.sql", "query5.sql",  unix_timestamp();
!run query50.sql;
SELECT "MARKER", "query51.sql", "query50.sql",  unix_timestamp();
!run query51.sql;
SELECT "MARKER", "query52.sql", "query51.sql",  unix_timestamp();
!run query52.sql;
SELECT "MARKER", "query53.sql", "query52.sql",  unix_timestamp();
!run query53.sql;
SELECT "MARKER", "query54.sql", "query53.sql",  unix_timestamp();
!run query54.sql;
SELECT "MARKER", "query55.sql", "query54.sql",  unix_timestamp();
!run query55.sql;
SELECT "MARKER", "query56.sql", "query55.sql",  unix_timestamp();
!run query56.sql;
SELECT "MARKER", "query57.sql", "query56.sql",  unix_timestamp();
!run query57.sql;
SELECT "MARKER", "query58.sql", "query57.sql",  unix_timestamp();
!run query58.sql;
SELECT "MARKER", "query59.sql", "query58.sql",  unix_timestamp();
!run query59.sql;
SELECT "MARKER", "query6.sql", "query59.sql",  unix_timestamp();
!run query6.sql;
SELECT "MARKER", "query60.sql", "query6.sql",  unix_timestamp();
!run query60.sql;
SELECT "MARKER", "query61.sql", "query60.sql",  unix_timestamp();
!run query61.sql;
SELECT "MARKER", "query62.sql", "query61.sql",  unix_timestamp();
!run query62.sql;
SELECT "MARKER", "query63.sql", "query62.sql",  unix_timestamp();
!run query63.sql;
SELECT "MARKER", "query64.sql", "query63.sql",  unix_timestamp();
!run query64.sql;
SELECT "MARKER", "query65.sql", "query64.sql",  unix_timestamp();
!run query65.sql;
SELECT "MARKER", "query66.sql", "query65.sql",  unix_timestamp();
!run query66.sql;
SELECT "MARKER", "query67.sql", "query66.sql",  unix_timestamp();
!run query67.sql;
SELECT "MARKER", "query68.sql", "query67.sql",  unix_timestamp();
!run query68.sql;
SELECT "MARKER", "query69.sql", "query68.sql",  unix_timestamp();
!run query69.sql;
SELECT "MARKER", "query7.sql", "query69.sql",  unix_timestamp();
!run query7.sql;
SELECT "MARKER", "query70.sql", "query7.sql",  unix_timestamp();
!run query70.sql;
SELECT "MARKER", "query71.sql", "query70.sql",  unix_timestamp();
!run query71.sql;
SELECT "MARKER", "query72.sql", "query71.sql",  unix_timestamp();
!run query72.sql;
SELECT "MARKER", "query73.sql", "query72.sql",  unix_timestamp();
!run query73.sql;
SELECT "MARKER", "query74.sql", "query73.sql",  unix_timestamp();
!run query74.sql;
SELECT "MARKER", "query75.sql", "query74.sql",  unix_timestamp();
!run query75.sql;
SELECT "MARKER", "query76.sql", "query75.sql",  unix_timestamp();
!run query76.sql;
SELECT "MARKER", "query77.sql", "query76.sql",  unix_timestamp();
!run query77.sql;
SELECT "MARKER", "query78.sql", "query77.sql",  unix_timestamp();
!run query78.sql;
SELECT "MARKER", "query79.sql", "query78.sql",  unix_timestamp();
!run query79.sql;
SELECT "MARKER", "query8.sql", "query79.sql",  unix_timestamp();
!run query8.sql;
SELECT "MARKER", "query80.sql", "query8.sql",  unix_timestamp();
!run query80.sql;
SELECT "MARKER", "query81.sql", "query80.sql",  unix_timestamp();
!run query81.sql;
SELECT "MARKER", "query82.sql", "query81.sql",  unix_timestamp();
!run query82.sql;
SELECT "MARKER", "query83.sql", "query82.sql",  unix_timestamp();
!run query83.sql;
SELECT "MARKER", "query84.sql", "query83.sql",  unix_timestamp();
!run query84.sql;
SELECT "MARKER", "query85.sql", "query84.sql",  unix_timestamp();
!run query85.sql;
SELECT "MARKER", "query86.sql", "query85.sql",  unix_timestamp();
!run query86.sql;
SELECT "MARKER", "query87.sql", "query86.sql",  unix_timestamp();
!run query87.sql;
SELECT "MARKER", "query88.sql", "query87.sql",  unix_timestamp();
!run query88.sql;
SELECT "MARKER", "query89.sql", "query88.sql",  unix_timestamp();
!run query89.sql;
SELECT "MARKER", "query9.sql", "query89.sql",  unix_timestamp();
!run query9.sql;
SELECT "MARKER", "query90.sql", "query9.sql",  unix_timestamp();
!run query90.sql;
SELECT "MARKER", "query91.sql", "query90.sql",  unix_timestamp();
!run query91.sql;
SELECT "MARKER", "query92.sql", "query91.sql",  unix_timestamp();
!run query92.sql;
SELECT "MARKER", "query93.sql", "query92.sql",  unix_timestamp();
!run query93.sql;
SELECT "MARKER", "query94.sql", "query93.sql",  unix_timestamp();
!run query94.sql;
SELECT "MARKER", "query95.sql", "query94.sql",  unix_timestamp();
!run query95.sql;
SELECT "MARKER", "query96.sql", "query95.sql",  unix_timestamp();
!run query96.sql;
SELECT "MARKER", "query97.sql", "query96.sql",  unix_timestamp();
!run query97.sql;
SELECT "MARKER", "query98.sql", "query97.sql",  unix_timestamp();
!run query98.sql;
SELECT "MARKER", "query99.sql", "query98.sql",  unix_timestamp();
!run query99.sql;
SELECT "MARKER", "", "query99.sql",  unix_timestamp();
!record
